<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE program [ 
  <!ELEMENT program (taci+)>
  <!ELEMENT taci (dst?,src1?,src2?)>
  <!ELEMENT dst (#PCDATA)>
  <!ELEMENT src1 (#PCDATA)>
  <!ELEMENT src2 (#PCDATA)>
  <!ATTLIST program name CDATA #IMPLIED>
  <!ATTLIST taci opcode CDATA #REQUIRED>
  <!ATTLIST dst kind (literal|variable) "variable">
  <!ATTLIST dst type (integer|string) "integer">
  <!ATTLIST src1 kind (literal|variable) "variable">
  <!ATTLIST src1 type (integer|string) "integer">
  <!ATTLIST src2 kind (literal|variable) "variable">
  <!ATTLIST src2 type (integer|string) "integer">
  <!ENTITY language "IPPe Three-Address Code">
  <!ENTITY eol "&#xA;">
  <!ENTITY gt ">">
  <!ENTITY lt "<">
]>
<program name="Factorial (using &language;)">
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">Print factorial of number</src1>
  </taci>
  <taci opcode="JUMP">
    <dst kind="literal" type="string">MAIN</dst>
  </taci>
  <taci opcode="LABEL">
    <dst kind="literal" type="string">FACTORIAL</dst>
  </taci>
  <taci opcode="POP">
    <dst>n</dst>
  </taci>  
  <taci opcode="JUMPIFEQ">
    <dst kind="literal" type="string">RETURN1</dst>
    <src1>n</src1>
    <src2 kind="literal">0</src2>
  </taci>
  <taci opcode="JUMPIFEQ">
    <dst kind="literal" type="string">RETURN1</dst>
    <src1>n</src1>
    <src2 kind="literal">1</src2>
  </taci>
  
  <taci opcode="SUB">
    <dst>m</dst>
    <src1>n</src1>
    <src2 kind="literal">1</src2>
  </taci>
  
    <!-- recursive call of FACTORIAL -->
    <taci opcode="PUSH"><src1>n</src1></taci> <!-- save context -->
    <taci opcode="PUSH"><src1>m</src1></taci> <!-- send parameter -->
    <taci opcode="CALL"><dst kind="literal" type="string">FACTORIAL</dst></taci>
    <taci opcode="POP"><dst>m</dst></taci> <!-- result of fun-call -->
    <taci opcode="POP"><dst>n</dst></taci> <!-- restore context -->

  <taci opcode="MUL">
    <dst>m</dst>
    <src1>n</src1>
    <src2>m</src2>
  </taci>
    
  <taci opcode="PUSH">
    <src1>m</src1>
  </taci>
  <taci opcode="RETURN">
  </taci>
  <taci opcode="LABEL">
    <dst kind="literal" type="string">RETURN1</dst>
  </taci>
  <taci opcode="PUSH">
    <src1 kind="literal">1</src1>
  </taci>  
  <taci opcode="RETURN">
  </taci>
  <taci opcode="PRINT">
    <src1 kind="literal" type="string">This line should not be printed&lt;!&gt;</src1>
  </taci>   
  <taci opcode="LABEL">
    <dst kind="literal" type="string">MAIN</dst>
  </taci>
  <taci opcode="READINT">
    <dst>number</dst>
  </taci>  
  <taci opcode="PUSH">
    <src1>number</src1>
  </taci>  
  <taci opcode="CALL">
    <dst kind="literal" type="string">FACTORIAL</dst>  
  </taci>
  <taci opcode="POP">
    <dst>result</dst>
  </taci>
  <taci opcode="PRINT">
    <src1>result</src1>
  </taci>  

</program> 